### ISSUE TITLE
Advice for running in a sandbox: Invalid Host Header

### ISSUE THREAD

**Issue by ocdtrekkie** [HVF/franchise#13]
Any idea how I can combat the "Invalid Host Header" error? I am trying to see if I can get this running in a Sandstorm instance, but I don't know enough about webpack to figure out how to successfully disable this check. I tried adding --offline and --host 0.0.0.0 in the package file for yarn start.

**Comment by bissonex** [comment]
Try to bundle the application:
> yarn run build

Then you can use the bundle/ directory.

**Comment by ocdtrekkie** [comment]
@bissonex How do I "use" the bundle/ directory once I build? (I'm not able to try this right this moment, so I apologize if it should be apparent.)

**Comment by bissonex** [comment]
Push the bundle/ to your public folder.

```
A good "ready-to-use tool" option with Node.js could be http-server:

>npm install http-server -g
To use it:

>cd bundle
>http-server
```

**Comment by bijection** [comment]
Hey all! Thanks for sitting tight. We now have canonicalized instructions for local deployment [here](https://github.com/HVF/franchise/blob/master/DEPLOYING_LOCALLY.md ).
