### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by flaviomarcheni** [HVF/franchise#16]
Exists any docker image?

**Comment by liuzhuoling2011** [comment]
https://store.docker.com/community/images/psychemedia/franchise

**Comment by binakot** [comment]
Also there are:
* https://hub.docker.com/r/carto/franchise
* https://hub.docker.com/r/jsoizo/franchise
* https://hub.docker.com/r/felixleung/franchise
* https://hub.docker.com/r/cliffom/franchise

What about to build official Docker image?

**Comment by binakot** [comment]
Btw I deployed my own Docker image with built-in `franchise-client` in the same container. https://hub.docker.com/r/binakot/franchise

**Comment by binakot** [comment]
Now after the merge of https://github.com/HVF/franchise/pull/68 you can build or use official Docker image from this repo.
