### ISSUE TITLE
Dist App Not Working

### ISSUE THREAD

**Issue by ozguncagri** [HVF/franchise#2]
Hey, I used your online demo and I really liked it but when I try to build it I had problem that says you have to remove "electron" package from dependencies. I removed it on package.json file then build with "yarn dist" command. It created application but app is not starting. App is stuck on this screen:

![screen shot 2017-09-15 at 11 39 09](https://user-images.githubusercontent.com/946294/30473879-823c417c-9a0a-11e7-9505-0ac9a8f9ef62.png)

So my question is can you pre-build app and release binaries on releases section on github?

Thanks

**Comment by bijection** [comment]
We're still working on the electron app.

In the mean time you should be able to use the local version by running `yarn start`.
