### ISSUE TITLE
publish instance location & port

### ISSUE THREAD

**Issue by bmd-andyputra** [HVF/franchise#29]
Hi,

I want to change from http://localhost to our server instance name --> where can I do that? and also for port. because if i run franchise in default, i got error
"invalid host header"

**Comment by krisoul** [comment]
same, how to change it?

**Comment by ekka21** [comment]
I still run into "invalid host header" issue. Is there a way to disableHostCheck?

**Comment by bijection** [comment]
We've written up instructions for deploying locally [here](https://github.com/HVF/franchise/blob/master/DEPLOYING_LOCALLY.md).

In light of this I'm closing this issue, but feel free to keep commenting here if the writeup is unclear.
