### ISSUE TITLE
Install script is missing some dependencies

### ISSUE THREAD

**Issue by AbelVM** [HVF/franchise#35]
In Ubuntu 17 environment I needed the following modules that were not listed in the dependencies
* prop-types
* uglify-js
* nwb

**Comment by bijection** [comment]
Did you run into this problem using npm or yarn?

**Comment by AbelVM** [comment]
npm

**Comment by AbelVM** [comment]
Looks like it was caused by a one-in-a-million combination of node/yarn/npm versions that caused an unexpected and random behavior of the install script, not related with the code itself. Closing.
