### ISSUE TITLE
franchise client error: core_1.Utils.shallowCompareKeys is not a function

### ISSUE THREAD

**Issue by gangachris** [HVF/franchise#39]
Whenever I run any query, I get this ` core_1.Utils.shallowCompareKeys is not a function`
<img width="1291" alt="screen shot 2017-09-29 at 14 07 17" src="https://user-images.githubusercontent.com/3910877/31013650-bae5e2b0-a51f-11e7-84c7-0591534800a9.png">
Is there something I'm missing?. This is a local instance

**Comment by bijection** [comment]
What OS / node version / browser are you using?
