### ISSUE TITLE
Interested in adding GraphQL and Cypher support

### ISSUE THREAD

**Issue by kbrandwijk** [HVF/franchise#40]
I love the platform, and the visualization options. It would be very powerful to also be able to use this tool for Cypher queries and GraphQL queries!

**Comment by bijection** [comment]
Glad you like franchise!
Do you mean that you're interested in adding support (personally), or interested in support being added (by someone else)?

**Comment by kbrandwijk** [comment]
Well, either actually.

**Comment by bijection** [comment]
Great - we're planning on writing up a doc detailing the process for adding connectors, but in the meantime we would love to walk you through adding support if you'd be amenable!

**Comment by bijection** [comment]
@kbrandwijk How would you like to proceed?

**Comment by kbrandwijk** [comment]
I'll have time to go over the codebase next week. If you don't plan on having that document by then, maybe we can set up something else to go over it.

**Comment by kbrandwijk** [comment]
It's been a while, but I have gone over the code, and I have started the implementation for GraphQL. At this point, everything seems clear, the code is well structured.

**Comment by kbrandwijk** [comment]
This has been dead in the water for a while now, do you think my efforts could lead to a PR in your main repo?

**Comment by antimatter15** [comment]
Yeah, if you submit it as a pull request we'll merge it like we did with CARTO.

**Comment by antimatter15** [comment]
GraphQL support has been added in #71
