### ISSUE TITLE
"npx franchise-client@0.2.4" fails

### ISSUE THREAD

**Issue by wngmnheiko** [HVF/franchise#42]
[2017-10-02T08_43_52_006Z-debug.log](https://github.com/HVF/franchise/files/1348983/2017-10-02T08_43_52_006Z-debug.log)
Maybe this is a bug with npm or npx, but I'm unable to start the franchise-client.
OS is macOS Sierra Version 10.12.6, node version is v8.6.0 and npm version is v5.3.0.

MacBook-Air:SomeDir$ LANG=en npx franchise-client@0.2.4
npm ERR! path /Users/heiko/.npm/_npx/6099/lib/node_modules/franchise-client/lib/server.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/Users/heiko/.npm/_npx/6099/lib/node_modules/franchise-client/lib/server.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm E
[2017-10-02T08_43_52_006Z-debug.log](https://github.com/HVF/franchise/files/1348348/2017-10-02T08_43_52_006Z-debug.log)
RR!     /Users/heiko/.npm/_logs/2017-10-02T08_43_52_006Z-debug.log
Install for franchise-client@0.2.4 failed with code 254

The directory /Users/heiko/.npm/_npx/ is completely empty.

**Comment by c0bra** [comment]
`npm install -g franchise-client` fails with the same error

**Comment by bijection** [comment]
This should be fixed with franchise-client version 0.2.7
The UI has been updated with the new version number.
