### ISSUE TITLE
Use as desktop app in electron

### ISSUE THREAD

**Issue by alfredopalhares** [HVF/franchise#49]
Hello,

Is it in the plan to make a desktop version using electron?  It would be a nice way to package it onto desktops.

Regards,
Alfredo Palhares

**Comment by antimatter15** [comment]
There’s already an electron app in the repo but it still needs a bit more
work

**Comment by aveekdeveloper** [comment]
Can you tell me how to use the electron app? I am behind a corporate firewall and the bridge doesn't work for me. I would prefer to have everything run locally...

**Comment by binakot** [comment]
After the merge of https://github.com/HVF/franchise/pull/68 you can build Electron app. Read the last point in README file, please.
