### ISSUE TITLE
"missing ) after argument list" when trying to run franchise-client

### ISSUE THREAD

**Issue by joshstrange** [HVF/franchise#6]
````
> npx franchise-client                                                                                                                                                         
npx: installed 140 in 7.431s
missing ) after argument list
````

````
npm: 5.3.0
node: v6.5.0
````

**Comment by bijection** [comment]
Updating node should fix this problem.

**Comment by thane421** [comment]
even with the latest LTS node version (6.11.3) I was having this issue.
I switched to node 8 and it solved the problem, but I'm not sure that's what was intended.

**Comment by antimatter15** [comment]
Seems to have been a stray comma in `franchise-client` Fixed in https://github.com/HVF/franchise-client/commit/2e98fb29b5f02b641c307f498d2821c48b86d6b3

**Comment by bijection** [comment]
@thane421 whoops, thanks for testing different node versions!
