### ISSUE TITLE
Help with bridge set-up

### ISSUE THREAD

**Issue by elad-eyal** [HVF/franchise#89]
So the docs promise that you need just a single line in order to enable mysql connectivity right? But I can't find any documentation for what that line actually is.

**Comment by pyrho** [comment]
`npx franchise-client@0.2.7` the message only shows when you reach [this](https://franchise.cloud/app/) page.

![Screenshot from 2021-04-28 20-16-52](https://user-images.githubusercontent.com/145502/116453068-f1f14080-a84d-11eb-8cf8-bac4f801874d.png)
